#!/bin/bash

git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
git config branch.autosetuprebase always
git config --global core.editor nvim
git config --global core.excludesfile ~/.gitignore_global
