#!/bin/bash
# Add some PPAs
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update

# Install!
sudo apt-get install vim
sudo apt-get install openssh-server
sudo apt-get install screen
sudo apt-get install psensor
sudo apt-get install gnome-tweak-tool
sudo apt-get install sublime-text-installer
